import os
from pathlib import Path
import re

# Base directory
BASE_DIR = r"C:/Users/BalasubramanianPG/Videos/Obsidian Vault/3. Interview Prep/M Query"

# Categories and topics
categories = {
    "Data Ingestion": [
        "Connect to SQL Server for large datasets",
        "Connect to SQL Server with query folding considerations",
        "Connect to SQL Server without query folding",
        "Connect to SQL Server as a reusable function",
        "Connect to SQL Server optimized for incremental refresh",
        "Connect to SQL Server with error handling and retries",
        "Connect to SQL Server for multi-tenant scenarios",
        "Connect to SQL Server with GDPR/Privacy constraints",
        "Import Excel Workbook for large datasets",
        "Import Excel Workbook with query folding considerations",
        "Import Excel Workbook without query folding",
        "Import Excel Workbook as a reusable function",
        "Import Excel Workbook optimized for incremental refresh",
        "Import Excel Workbook with error handling and retries",
        "Import Excel Workbook for multi-tenant scenarios",
        "Import Excel Workbook with GDPR/Privacy constraints",
        "Read CSV File for large datasets",
        "Read CSV File with query folding considerations",
        "Read CSV File without query folding",
        "Read CSV File as a reusable function",
        "Read CSV File optimized for incremental refresh",
        "Read CSV File with error handling and retries",
        "Read CSV File for multi-tenant scenarios",
        "Read CSV File with GDPR/Privacy constraints",
        "Connect to REST API for large datasets",
        "Connect to REST API with query folding considerations",
        "Connect to REST API without query folding",
        "Connect to REST API as a reusable function",
        "Connect to REST API optimized for incremental refresh",
        "Connect to REST API with error handling and retries",
        "Connect to REST API for multi-tenant scenarios",
        "Connect to REST API with GDPR/Privacy constraints",
        "Import SharePoint File for large datasets",
        "Import SharePoint File with query folding considerations",
        "Import SharePoint File without query folding",
        "Import SharePoint File as a reusable function",
        "Import SharePoint File optimized for incremental refresh",
        "Import SharePoint File with error handling and retries",
        "Import SharePoint File for multi-tenant scenarios",
        "Import SharePoint File with GDPR/Privacy constraints",
        "Load JSON File for large datasets",
        "Load JSON File with query folding considerations",
        "Load JSON File without query folding",
        "Load JSON File as a reusable function",
        "Load JSON File optimized for incremental refresh",
        "Load JSON File with error handling and retries",
        "Load JSON File for multi-tenant scenarios",
        "Load JSON File with GDPR/Privacy constraints",
        "Import XML Data for large datasets",
        "Import XML Data with query folding considerations",
        "Import XML Data without query folding",
        "Import XML Data as a reusable function",
        "Import XML Data optimized for incremental refresh",
        "Import XML Data with error handling and retries",
        "Import XML Data for multi-tenant scenarios",
        "Import XML Data with GDPR/Privacy constraints",
        "Read Folder Files for large datasets",
        "Read Folder Files with query folding considerations",
        "Read Folder Files without query folding",
        "Read Folder Files as a reusable function",
        "Read Folder Files optimized for incremental refresh",
        "Read Folder Files with error handling and retries",
        "Read Folder Files for multi-tenant scenarios",
        "Read Folder Files with GDPR/Privacy constraints",
        "Connect to PostgreSQL for large datasets",
        "Connect to PostgreSQL with query folding considerations",
        "Connect to PostgreSQL without query folding",
        "Connect to PostgreSQL as a reusable function",
        "Connect to PostgreSQL optimized for incremental refresh",
        "Connect to PostgreSQL with error handling and retries",
        "Connect to PostgreSQL for multi-tenant scenarios",
        "Connect to PostgreSQL with GDPR/Privacy constraints",
        "Connect to MySQL for large datasets",
        "Connect to MySQL with query folding considerations",
        "Connect to MySQL without query folding",
        "Connect to MySQL as a reusable function",
        "Connect to MySQL optimized for incremental refresh",
        "Connect to MySQL with error handling and retries",
        "Connect to MySQL for multi-tenant scenarios",
        "Connect to MySQL with GDPR/Privacy constraints"
    ],

    "Data Cleaning": [
        "Promote Headers for large datasets",
        "Promote Headers with query folding considerations",
        "Promote Headers without query folding",
        "Promote Headers as a reusable function",
        "Promote Headers optimized for incremental refresh",
        "Promote Headers with error handling and retries",
        "Promote Headers for multi-tenant scenarios",
        "Promote Headers with GDPR/Privacy constraints",
        "Change Column Types for large datasets",
        "Change Column Types with query folding considerations",
        "Change Column Types without query folding",
        "Change Column Types as a reusable function",
        "Change Column Types optimized for incremental refresh",
        "Change Column Types with error handling and retries",
        "Change Column Types for multi-tenant scenarios",
        "Change Column Types with GDPR/Privacy constraints",
        "Remove Unnecessary Columns for large datasets",
        "Remove Unnecessary Columns with query folding considerations",
        "Remove Unnecessary Columns without query folding",
        "Remove Unnecessary Columns as a reusable function",
        "Remove Unnecessary Columns optimized for incremental refresh",
        "Remove Unnecessary Columns with error handling and retries",
        "Remove Unnecessary Columns for multi-tenant scenarios",
        "Remove Unnecessary Columns with GDPR/Privacy constraints",
        "Rename Columns for large datasets",
        "Rename Columns with query folding considerations",
        "Rename Columns without query folding",
        "Rename Columns as a reusable function",
        "Rename Columns optimized for incremental refresh",
        "Rename Columns with error handling and retries",
        "Rename Columns for multi-tenant scenarios",
        "Rename Columns with GDPR/Privacy constraints",
        "Replace Null Values for large datasets",
        "Replace Null Values with query folding considerations",
        "Replace Null Values without query folding",
        "Replace Null Values as a reusable function",
        "Replace Null Values optimized for incremental refresh",
        "Replace Null Values with error handling and retries",
        "Replace Null Values for multi-tenant scenarios",
        "Replace Null Values with GDPR/Privacy constraints",
        "Trim Text Columns for large datasets",
        "Trim Text Columns with query folding considerations",
        "Trim Text Columns without query folding",
        "Trim Text Columns as a reusable function",
        "Trim Text Columns optimized for incremental refresh",
        "Trim Text Columns with error handling and retries",
        "Trim Text Columns for multi-tenant scenarios",
        "Trim Text Columns with GDPR/Privacy constraints",
        "Clean Invalid Characters for large datasets",
        "Clean Invalid Characters with query folding considerations",
        "Clean Invalid Characters without query folding",
        "Clean Invalid Characters as a reusable function",
        "Clean Invalid Characters optimized for incremental refresh",
        "Clean Invalid Characters with error handling and retries",
        "Clean Invalid Characters for multi-tenant scenarios",
        "Clean Invalid Characters with GDPR/Privacy constraints",
        "Standardize Text Case for large datasets",
        "Standardize Text Case with query folding considerations",
        "Standardize Text Case without query folding",
        "Standardize Text Case as a reusable function",
        "Standardize Text Case optimized for incremental refresh",
        "Standardize Text Case with error handling and retries",
        "Standardize Text Case for multi-tenant scenarios",
        "Standardize Text Case with GDPR/Privacy constraints",
        "Remove Duplicate Rows for large datasets",
        "Remove Duplicate Rows with query folding considerations",
        "Remove Duplicate Rows without query folding",
        "Remove Duplicate Rows as a reusable function",
        "Remove Duplicate Rows optimized for incremental refresh",
        "Remove Duplicate Rows with error handling and retries",
        "Remove Duplicate Rows for multi-tenant scenarios",
        "Remove Duplicate Rows with GDPR/Privacy constraints",
        "Fill Down Missing Values for large datasets",
        "Fill Down Missing Values with query folding considerations",
        "Fill Down Missing Values without query folding",
        "Fill Down Missing Values as a reusable function",
        "Fill Down Missing Values optimized for incremental refresh",
        "Fill Down Missing Values with error handling and retries",
        "Fill Down Missing Values for multi-tenant scenarios",
        "Fill Down Missing Values with GDPR/Privacy constraints"
    ],

    "Data Transformation": [
        "Split Columns By Delimiter for large datasets",
        "Split Columns By Delimiter with query folding considerations",
        "Split Columns By Delimiter without query folding",
        "Split Columns By Delimiter as a reusable function",
        "Split Columns By Delimiter optimized for incremental refresh",
        "Split Columns By Delimiter with error handling and retries",
        "Split Columns By Delimiter for multi-tenant scenarios",
        "Split Columns By Delimiter with GDPR/Privacy constraints",
        "Merge Columns for large datasets",
        "Merge Columns with query folding considerations",
        "Merge Columns without query folding",
        "Merge Columns as a reusable function",
        "Merge Columns optimized for incremental refresh",
        "Merge Columns with error handling and retries",
        "Merge Columns for multi-tenant scenarios",
        "Merge Columns with GDPR/Privacy constraints",
        "Create Calculated Column for large datasets",
        "Create Calculated Column with query folding considerations",
        "Create Calculated Column without query folding",
        "Create Calculated Column as a reusable function",
        "Create Calculated Column optimized for incremental refresh",
        "Create Calculated Column with error handling and retries",
        "Create Calculated Column for multi-tenant scenarios",
        "Create Calculated Column with GDPR/Privacy constraints",
        "Pivot Table for large datasets",
        "Pivot Table with query folding considerations",
        "Pivot Table without query folding",
        "Pivot Table as a reusable function",
        "Pivot Table optimized for incremental refresh",
        "Pivot Table with error handling and retries",
        "Pivot Table for multi-tenant scenarios",
        "Pivot Table with GDPR/Privacy constraints",
        "Unpivot Table for large datasets",
        "Unpivot Table with query folding considerations",
        "Unpivot Table without query folding",
        "Unpivot Table as a reusable function",
        "Unpivot Table optimized for incremental refresh",
        "Unpivot Table with error handling and retries",
        "Unpivot Table for multi-tenant scenarios",
        "Unpivot Table with GDPR/Privacy constraints",
        "Transpose Table for large datasets",
        "Transpose Table with query folding considerations",
        "Transpose Table without query folding",
        "Transpose Table as a reusable function",
        "Transpose Table optimized for incremental refresh",
        "Transpose Table with error handling and retries",
        "Transpose Table for multi-tenant scenarios",
        "Transpose Table with GDPR/Privacy constraints",
        "Extract Substring for large datasets",
        "Extract Substring with query folding considerations",
        "Extract Substring without query folding",
        "Extract Substring as a reusable function",
        "Extract Substring optimized for incremental refresh",
        "Extract Substring with error handling and retries",
        "Extract Substring for multi-tenant scenarios",
        "Extract Substring with GDPR/Privacy constraints",
        "Parse Date From Text for large datasets",
        "Parse Date From Text with query folding considerations",
        "Parse Date From Text without query folding",
        "Parse Date From Text as a reusable function",
        "Parse Date From Text optimized for incremental refresh",
        "Parse Date From Text with error handling and retries",
        "Parse Date From Text for multi-tenant scenarios",
        "Parse Date From Text with GDPR/Privacy constraints",
        "Create Index Column for large datasets",
        "Create Index Column with query folding considerations",
        "Create Index Column without query folding",
        "Create Index Column as a reusable function",
        "Create Index Column optimized for incremental refresh",
        "Create Index Column with error handling and retries",
        "Create Index Column for multi-tenant scenarios",
        "Create Index Column with GDPR/Privacy constraints",
        "Group Rows By Category for large datasets",
        "Group Rows By Category with query folding considerations",
        "Group Rows By Category without query folding",
        "Group Rows By Category as a reusable function",
        "Group Rows By Category optimized for incremental refresh",
        "Group Rows By Category with error handling and retries",
        "Group Rows By Category for multi-tenant scenarios",
        "Group Rows By Category with GDPR/Privacy constraints"
    ],

    "Data Filtering": [
        "Filter Rows By Value for large datasets",
        "Filter Rows By Value with query folding considerations",
        "Filter Rows By Value without query folding",
        "Filter Rows By Value as a reusable function",
        "Filter Rows By Value optimized for incremental refresh",
        "Filter Rows By Value with error handling and retries",
        "Filter Rows By Value for multi-tenant scenarios",
        "Filter Rows By Value with GDPR/Privacy constraints",
        "Filter By Date Range for large datasets",
        "Filter By Date Range with query folding considerations",
        "Filter By Date Range without query folding",
        "Filter By Date Range as a reusable function",
        "Filter By Date Range optimized for incremental refresh",
        "Filter By Date Range with error handling and retries",
        "Filter By Date Range for multi-tenant scenarios",
        "Filter By Date Range with GDPR/Privacy constraints",
        "Remove Null Records for large datasets",
        "Remove Null Records with query folding considerations",
        "Remove Null Records without query folding",
        "Remove Null Records as a reusable function",
        "Remove Null Records optimized for incremental refresh",
        "Remove Null Records with error handling and retries",
        "Remove Null Records for multi-tenant scenarios",
        "Remove Null Records with GDPR/Privacy constraints",
        "Keep Top N Rows for large datasets",
        "Keep Top N Rows with query folding considerations",
        "Keep Top N Rows without query folding",
        "Keep Top N Rows as a reusable function",
        "Keep Top N Rows optimized for incremental refresh",
        "Keep Top N Rows with error handling and retries",
        "Keep Top N Rows for multi-tenant scenarios",
        "Keep Top N Rows with GDPR/Privacy constraints",
        "Keep Bottom N Rows for large datasets",
        "Keep Bottom N Rows with query folding considerations",
        "Keep Bottom N Rows without query folding",
        "Keep Bottom N Rows as a reusable function",
        "Keep Bottom N Rows optimized for incremental refresh",
        "Keep Bottom N Rows with error handling and retries",
        "Keep Bottom N Rows for multi-tenant scenarios",
        "Keep Bottom N Rows with GDPR/Privacy constraints",
        "Filter Text Contains for large datasets",
        "Filter Text Contains with query folding considerations",
        "Filter Text Contains without query folding",
        "Filter Text Contains as a reusable function",
        "Filter Text Contains optimized for incremental refresh",
        "Filter Text Contains with error handling and retries",
        "Filter Text Contains for multi-tenant scenarios",
        "Filter Text Contains with GDPR/Privacy constraints",
        "Filter By Multiple Conditions for large datasets",
        "Filter By Multiple Conditions with query folding considerations",
        "Filter By Multiple Conditions without query folding",
        "Filter By Multiple Conditions as a reusable function",
        "Filter By Multiple Conditions optimized for incremental refresh",
        "Filter By Multiple Conditions with error handling and retries",
        "Filter By Multiple Conditions for multi-tenant scenarios",
        "Filter By Multiple Conditions with GDPR/Privacy constraints",
        "Exclude Specific Values for large datasets",
        "Exclude Specific Values with query folding considerations",
        "Exclude Specific Values without query folding",
        "Exclude Specific Values as a reusable function",
        "Exclude Specific Values optimized for incremental refresh",
        "Exclude Specific Values with error handling and retries",
        "Exclude Specific Values for multi-tenant scenarios",
        "Exclude Specific Values with GDPR/Privacy constraints",
        "Filter Duplicate Records for large datasets",
        "Filter Duplicate Records with query folding considerations",
        "Filter Duplicate Records without query folding",
        "Filter Duplicate Records as a reusable function",
        "Filter Duplicate Records optimized for incremental refresh",
        "Filter Duplicate Records with error handling and retries",
        "Filter Duplicate Records for multi-tenant scenarios",
        "Filter Duplicate Records with GDPR/Privacy constraints",
        "Select Specific Columns for large datasets",
        "Select Specific Columns with query folding considerations",
        "Select Specific Columns without query folding",
        "Select Specific Columns as a reusable function",
        "Select Specific Columns optimized for incremental refresh",
        "Select Specific Columns with error handling and retries",
        "Select Specific Columns for multi-tenant scenarios",
        "Select Specific Columns with GDPR/Privacy constraints"
    ],

    "Data Combination": [
        "Join Two Tables for large datasets",
        "Join Two Tables with query folding considerations",
        "Join Two Tables without query folding",
        "Join Two Tables as a reusable function",
        "Join Two Tables optimized for incremental refresh",
        "Join Two Tables with error handling and retries",
        "Join Two Tables for multi-tenant scenarios",
        "Join Two Tables with GDPR/Privacy constraints",
        "Left Join Datasets for large datasets",
        "Left Join Datasets with query folding considerations",
        "Left Join Datasets without query folding",
        "Left Join Datasets as a reusable function",
        "Left Join Datasets optimized for incremental refresh",
        "Left Join Datasets with error handling and retries",
        "Left Join Datasets for multi-tenant scenarios",
        "Left Join Datasets with GDPR/Privacy constraints",
        "Right Join Datasets for large datasets",
        "Right Join Datasets with query folding considerations",
        "Right Join Datasets without query folding",
        "Right Join Datasets as a reusable function",
        "Right Join Datasets optimized for incremental refresh",
        "Right Join Datasets with error handling and retries",
        "Right Join Datasets for multi-tenant scenarios",
        "Right Join Datasets with GDPR/Privacy constraints",
        "Inner Join Datasets for large datasets",
        "Inner Join Datasets with query folding considerations",
        "Inner Join Datasets without query folding",
        "Inner Join Datasets as a reusable function",
        "Inner Join Datasets optimized for incremental refresh",
        "Inner Join Datasets with error handling and retries",
        "Inner Join Datasets for multi-tenant scenarios",
        "Inner Join Datasets with GDPR/Privacy constraints",
        "Full Outer Join for large datasets",
        "Full Outer Join with query folding considerations",
        "Full Outer Join without query folding",
        "Full Outer Join as a reusable function",
        "Full Outer Join optimized for incremental refresh",
        "Full Outer Join with error handling and retries",
        "Full Outer Join for multi-tenant scenarios",
        "Full Outer Join with GDPR/Privacy constraints",
        "Expand Nested Table for large datasets",
        "Expand Nested Table with query folding considerations",
        "Expand Nested Table without query folding",
        "Expand Nested Table as a reusable function",
        "Expand Nested Table optimized for incremental refresh",
        "Expand Nested Table with error handling and retries",
        "Expand Nested Table for multi-tenant scenarios",
        "Expand Nested Table with GDPR/Privacy constraints",
        "Append Multiple Tables for large datasets",
        "Append Multiple Tables with query folding considerations",
        "Append Multiple Tables without query folding",
        "Append Multiple Tables as a reusable function",
        "Append Multiple Tables optimized for incremental refresh",
        "Append Multiple Tables with error handling and retries",
        "Append Multiple Tables for multi-tenant scenarios",
        "Append Multiple Tables with GDPR/Privacy constraints",
        "Merge Fact And Dimension for large datasets",
        "Merge Fact And Dimension with query folding considerations",
        "Merge Fact And Dimension without query folding",
        "Merge Fact And Dimension as a reusable function",
        "Merge Fact And Dimension optimized for incremental refresh",
        "Merge Fact And Dimension with error handling and retries",
        "Merge Fact And Dimension for multi-tenant scenarios",
        "Merge Fact And Dimension with GDPR/Privacy constraints",
        "Combine Monthly Files for large datasets",
        "Combine Monthly Files with query folding considerations",
        "Combine Monthly Files without query folding",
        "Combine Monthly Files as a reusable function",
        "Combine Monthly Files optimized for incremental refresh",
        "Combine Monthly Files with error handling and retries",
        "Combine Monthly Files for multi-tenant scenarios",
        "Combine Monthly Files with GDPR/Privacy constraints",
        "Merge Sales With Customers for large datasets",
        "Merge Sales With Customers with query folding considerations",
        "Merge Sales With Customers without query folding",
        "Merge Sales With Customers as a reusable function",
        "Merge Sales With Customers optimized for incremental refresh",
        "Merge Sales With Customers with error handling and retries",
        "Merge Sales With Customers for multi-tenant scenarios",
        "Merge Sales With Customers with GDPR/Privacy constraints"
    ],

    "Automation": [
        "Combine All Files In Folder for large datasets",
        "Combine All Files In Folder with query folding considerations",
        "Combine All Files In Folder without query folding",
        "Combine All Files In Folder as a reusable function",
        "Combine All Files In Folder optimized for incremental refresh",
        "Combine All Files In Folder with error handling and retries",
        "Combine All Files In Folder for multi-tenant scenarios",
        "Combine All Files In Folder with GDPR/Privacy constraints",
        "Auto Load New Files for large datasets",
        "Auto Load New Files with query folding considerations",
        "Auto Load New Files without query folding",
        "Auto Load New Files as a reusable function",
        "Auto Load New Files optimized for incremental refresh",
        "Auto Load New Files with error handling and retries",
        "Auto Load New Files for multi-tenant scenarios",
        "Auto Load New Files with GDPR/Privacy constraints",
        "Parameterize Data Source for large datasets",
        "Parameterize Data Source with query folding considerations",
        "Parameterize Data Source without query folding",
        "Parameterize Data Source as a reusable function",
        "Parameterize Data Source optimized for incremental refresh",
        "Parameterize Data Source with error handling and retries",
        "Parameterize Data Source for multi-tenant scenarios",
        "Parameterize Data Source with GDPR/Privacy constraints",
        "Dynamic File Path for large datasets",
        "Dynamic File Path with query folding considerations",
        "Dynamic File Path without query folding",
        "Dynamic File Path as a reusable function",
        "Dynamic File Path optimized for incremental refresh",
        "Dynamic File Path with error handling and retries",
        "Dynamic File Path for multi-tenant scenarios",
        "Dynamic File Path with GDPR/Privacy constraints",
        "Build Reusable Function for large datasets",
        "Build Reusable Function with query folding considerations",
        "Build Reusable Function without query folding",
        "Build Reusable Function as a reusable function",
        "Build Reusable Function optimized for incremental refresh",
        "Build Reusable Function with error handling and retries",
        "Build Reusable Function for multi-tenant scenarios",
        "Build Reusable Function with GDPR/Privacy constraints",
        "Loop Through File List for large datasets",
        "Loop Through File List with query folding considerations",
        "Loop Through File List without query folding",
        "Loop Through File List as a reusable function",
        "Loop Through File List optimized for incremental refresh",
        "Loop Through File List with error handling and retries",
        "Loop Through File List for multi-tenant scenarios",
        "Loop Through File List with GDPR/Privacy constraints",
        "Schedule Data Refresh for large datasets",
        "Schedule Data Refresh with query folding considerations",
        "Schedule Data Refresh without query folding",
        "Schedule Data Refresh as a reusable function",
        "Schedule Data Refresh optimized for incremental refresh",
        "Schedule Data Refresh with error handling and retries",
        "Schedule Data Refresh for multi-tenant scenarios",
        "Schedule Data Refresh with GDPR/Privacy constraints",
        "Dynamic Date Filter for large datasets",
        "Dynamic Date Filter with query folding considerations",
        "Dynamic Date Filter without query folding",
        "Dynamic Date Filter as a reusable function",
        "Dynamic Date Filter optimized for incremental refresh",
        "Dynamic Date Filter with error handling and retries",
        "Dynamic Date Filter for multi-tenant scenarios",
        "Dynamic Date Filter with GDPR/Privacy constraints",
        "Generate Parameter Table for large datasets",
        "Generate Parameter Table with query folding considerations",
        "Generate Parameter Table without query folding",
        "Generate Parameter Table as a reusable function",
        "Generate Parameter Table optimized for incremental refresh",
        "Generate Parameter Table with error handling and retries",
        "Generate Parameter Table for multi-tenant scenarios",
        "Generate Parameter Table with GDPR/Privacy constraints",
        "Dynamic API Pagination for large datasets",
        "Dynamic API Pagination with query folding considerations",
        "Dynamic API Pagination without query folding",
        "Dynamic API Pagination as a reusable function",
        "Dynamic API Pagination optimized for incremental refresh",
        "Dynamic API Pagination with error handling and retries",
        "Dynamic API Pagination for multi-tenant scenarios",
        "Dynamic API Pagination with GDPR/Privacy constraints"
    ],

    "Performance & Optimization": [
        "Enable Query Folding for large datasets",
        "Enable Query Folding with query folding considerations",
        "Enable Query Folding without query folding",
        "Enable Query Folding as a reusable function",
        "Enable Query Folding optimized for incremental refresh",
        "Enable Query Folding with error handling and retries",
        "Enable Query Folding for multi-tenant scenarios",
        "Enable Query Folding with GDPR/Privacy constraints",
        "Optimize for Incremental Refresh for large datasets",
        "Optimize for Incremental Refresh with query folding considerations",
        "Optimize for Incremental Refresh without query folding",
        "Optimize for Incremental Refresh as a reusable function",
        "Optimize for Incremental Refresh optimized for incremental refresh",
        "Optimize for Incremental Refresh with error handling and retries",
        "Optimize for Incremental Refresh for multi-tenant scenarios",
        "Optimize for Incremental Refresh with GDPR/Privacy constraints",
        "Reduce Memory Footprint for large datasets",
        "Reduce Memory Footprint with query folding considerations",
        "Reduce Memory Footprint without query folding",
        "Reduce Memory Footprint as a reusable function",
        "Reduce Memory Footprint optimized for incremental refresh",
        "Reduce Memory Footprint with error handling and retries",
        "Reduce Memory Footprint for multi-tenant scenarios",
        "Reduce Memory Footprint with GDPR/Privacy constraints",
        "Push Transformations to Source for large datasets",
        "Push Transformations to Source with query folding considerations",
        "Push Transformations to Source without query folding",
        "Push Transformations to Source as a reusable function",
        "Push Transformations to Source optimized for incremental refresh",
        "Push Transformations to Source with error handling and retries",
        "Push Transformations to Source for multi-tenant scenarios",
        "Push Transformations to Source with GDPR/Privacy constraints",
        "Minimize Column Scans for large datasets",
        "Minimize Column Scans with query folding considerations",
        "Minimize Column Scans without query folding",
        "Minimize Column Scans as a reusable function",
        "Minimize Column Scans optimized for incremental refresh",
        "Minimize Column Scans with error handling and retries",
        "Minimize Column Scans for multi-tenant scenarios",
        "Minimize Column Scans with GDPR/Privacy constraints",
        "Parallelize File Processing for large datasets",
        "Parallelize File Processing with query folding considerations",
        "Parallelize File Processing without query folding",
        "Parallelize File Processing as a reusable function",
        "Parallelize File Processing optimized for incremental refresh",
        "Parallelize File Processing with error handling and retries",
        "Parallelize File Processing for multi-tenant scenarios",
        "Parallelize File Processing with GDPR/Privacy constraints",
        "Optimize Merge Strategies for large datasets",
        "Optimize Merge Strategies with query folding considerations",
        "Optimize Merge Strategies without query folding",
        "Optimize Merge Strategies as a reusable function",
        "Optimize Merge Strategies optimized for incremental refresh",
        "Optimize Merge Strategies with error handling and retries",
        "Optimize Merge Strategies for multi-tenant scenarios",
        "Optimize Merge Strategies with GDPR/Privacy constraints",
        "Use Table.Buffer Wisely for large datasets",
        "Use Table.Buffer Wisely with query folding considerations",
        "Use Table.Buffer Wisely without query folding",
        "Use Table.Buffer Wisely as a reusable function",
        "Use Table.Buffer Wisely optimized for incremental refresh",
        "Use Table.Buffer Wisely with error handling and retries",
        "Use Table.Buffer Wisely for multi-tenant scenarios",
        "Use Table.Buffer Wisely with GDPR/Privacy constraints",
        "Optimize Connectors for large datasets",
        "Optimize Connectors with query folding considerations",
        "Optimize Connectors without query folding",
        "Optimize Connectors as a reusable function",
        "Optimize Connectors optimized for incremental refresh",
        "Optimize Connectors with error handling and retries",
        "Optimize Connectors for multi-tenant scenarios",
        "Optimize Connectors with GDPR/Privacy constraints",
        "Tune Custom Functions for large datasets",
        "Tune Custom Functions with query folding considerations",
        "Tune Custom Functions without query folding",
        "Tune Custom Functions as a reusable function",
        "Tune Custom Functions optimized for incremental refresh",
        "Tune Custom Functions with error handling and retries",
        "Tune Custom Functions for multi-tenant scenarios",
        "Tune Custom Functions with GDPR/Privacy constraints"
    ],

    "Debugging, Testing & Validation": [
        "Add Row-level Logging for large datasets",
        "Add Row-level Logging with query folding considerations",
        "Add Row-level Logging without query folding",
        "Add Row-level Logging as a reusable function",
        "Add Row-level Logging optimized for incremental refresh",
        "Add Row-level Logging with error handling and retries",
        "Add Row-level Logging for multi-tenant scenarios",
        "Add Row-level Logging with GDPR/Privacy constraints",
        "Unit Test M Functions for large datasets",
        "Unit Test M Functions with query folding considerations",
        "Unit Test M Functions without query folding",
        "Unit Test M Functions as a reusable function",
        "Unit Test M Functions optimized for incremental refresh",
        "Unit Test M Functions with error handling and retries",
        "Unit Test M Functions for multi-tenant scenarios",
        "Unit Test M Functions with GDPR/Privacy constraints",
        "Validate Schema Changes for large datasets",
        "Validate Schema Changes with query folding considerations",
        "Validate Schema Changes without query folding",
        "Validate Schema Changes as a reusable function",
        "Validate Schema Changes optimized for incremental refresh",
        "Validate Schema Changes with error handling and retries",
        "Validate Schema Changes for multi-tenant scenarios",
        "Validate Schema Changes with GDPR/Privacy constraints",
        "Detect Null Injection for large datasets",
        "Detect Null Injection with query folding considerations",
        "Detect Null Injection without query folding",
        "Detect Null Injection as a reusable function",
        "Detect Null Injection optimized for incremental refresh",
        "Detect Null Injection with error handling and retries",
        "Detect Null Injection for multi-tenant scenarios",
        "Detect Null Injection with GDPR/Privacy constraints",
        "Create Data Quality Dashboards for large datasets",
        "Create Data Quality Dashboards with query folding considerations",
        "Create Data Quality Dashboards without query folding",
        "Create Data Quality Dashboards as a reusable function",
        "Create Data Quality Dashboards optimized for incremental refresh",
        "Create Data Quality Dashboards with error handling and retries",
        "Create Data Quality Dashboards for multi-tenant scenarios",
        "Create Data Quality Dashboards with GDPR/Privacy constraints",
        "Simulate Failure Modes for large datasets",
        "Simulate Failure Modes with query folding considerations",
        "Simulate Failure Modes without query folding",
        "Simulate Failure Modes as a reusable function",
        "Simulate Failure Modes optimized for incremental refresh",
        "Simulate Failure Modes with error handling and retries",
        "Simulate Failure Modes for multi-tenant scenarios",
        "Simulate Failure Modes with GDPR/Privacy constraints",
        "Track Step Execution Time for large datasets",
        "Track Step Execution Time with query folding considerations",
        "Track Step Execution Time without query folding",
        "Track Step Execution Time as a reusable function",
        "Track Step Execution Time optimized for incremental refresh",
        "Track Step Execution Time with error handling and retries",
        "Track Step Execution Time for multi-tenant scenarios",
        "Track Step Execution Time with GDPR/Privacy constraints",
        "Audit Data Lineage for large datasets",
        "Audit Data Lineage with query folding considerations",
        "Audit Data Lineage without query folding",
        "Audit Data Lineage as a reusable function",
        "Audit Data Lineage optimized for incremental refresh",
        "Audit Data Lineage with error handling and retries",
        "Audit Data Lineage for multi-tenant scenarios",
        "Audit Data Lineage with GDPR/Privacy constraints",
        "Replay Transformations for large datasets",
        "Replay Transformations with query folding considerations",
        "Replay Transformations without query folding",
        "Replay Transformations as a reusable function",
        "Replay Transformations optimized for incremental refresh",
        "Replay Transformations with error handling and retries",
        "Replay Transformations for multi-tenant scenarios",
        "Replay Transformations with GDPR/Privacy constraints",
        "Assert Row Counts for large datasets",
        "Assert Row Counts with query folding considerations",
        "Assert Row Counts without query folding",
        "Assert Row Counts as a reusable function",
        "Assert Row Counts optimized for incremental refresh",
        "Assert Row Counts with error handling and retries",
        "Assert Row Counts for multi-tenant scenarios",
        "Assert Row Counts with GDPR/Privacy constraints"
    ],

    "Security, Governance & Compliance": [
        "Mask Sensitive Columns for large datasets",
        "Mask Sensitive Columns with query folding considerations",
        "Mask Sensitive Columns without query folding",
        "Mask Sensitive Columns as a reusable function",
        "Mask Sensitive Columns optimized for incremental refresh",
        "Mask Sensitive Columns with error handling and retries",
        "Mask Sensitive Columns for multi-tenant scenarios",
        "Mask Sensitive Columns with GDPR/Privacy constraints",
        "Apply Row Level Security for large datasets",
        "Apply Row Level Security with query folding considerations",
        "Apply Row Level Security without query folding",
        "Apply Row Level Security as a reusable function",
        "Apply Row Level Security optimized for incremental refresh",
        "Apply Row Level Security with error handling and retries",
        "Apply Row Level Security for multi-tenant scenarios",
        "Apply Row Level Security with GDPR/Privacy constraints",
        "Audit Data Access for large datasets",
        "Audit Data Access with query folding considerations",
        "Audit Data Access without query folding",
        "Audit Data Access as a reusable function",
        "Audit Data Access optimized for incremental refresh",
        "Audit Data Access with error handling and retries",
        "Audit Data Access for multi-tenant scenarios",
        "Audit Data Access with GDPR/Privacy constraints",
        "Enforce Data Retention Policy for large datasets",
        "Enforce Data Retention Policy with query folding considerations",
        "Enforce Data Retention Policy without query folding",
        "Enforce Data Retention Policy as a reusable function",
        "Enforce Data Retention Policy optimized for incremental refresh",
        "Enforce Data Retention Policy with error handling and retries",
        "Enforce Data Retention Policy for multi-tenant scenarios",
        "Enforce Data Retention Policy with GDPR/Privacy constraints",
        "Encrypt At-Rest Metadata for large datasets",
        "Encrypt At-Rest Metadata with query folding considerations",
        "Encrypt At-Rest Metadata without query folding",
        "Encrypt At-Rest Metadata as a reusable function",
        "Encrypt At-Rest Metadata optimized for incremental refresh",
        "Encrypt At-Rest Metadata with error handling and retries",
        "Encrypt At-Rest Metadata for multi-tenant scenarios",
        "Encrypt At-Rest Metadata with GDPR/Privacy constraints",
        "Detect PII Patterns for large datasets",
        "Detect PII Patterns with query folding considerations",
        "Detect PII Patterns without query folding",
        "Detect PII Patterns as a reusable function",
        "Detect PII Patterns optimized for incremental refresh",
        "Detect PII Patterns with error handling and retries",
        "Detect PII Patterns for multi-tenant scenarios",
        "Detect PII Patterns with GDPR/Privacy constraints",
        "Filter Based On Compliance Flags for large datasets",
        "Filter Based On Compliance Flags with query folding considerations",
        "Filter Based On Compliance Flags without query folding",
        "Filter Based On Compliance Flags as a reusable function",
        "Filter Based On Compliance Flags optimized for incremental refresh",
        "Filter Based On Compliance Flags with error handling and retries",
        "Filter Based On Compliance Flags for multi-tenant scenarios",
        "Filter Based On Compliance Flags with GDPR/Privacy constraints",
        "Integrate With Azure AD for large datasets",
        "Integrate With Azure AD with query folding considerations",
        "Integrate With Azure AD without query folding",
        "Integrate With Azure AD as a reusable function",
        "Integrate With Azure AD optimized for incremental refresh",
        "Integrate With Azure AD with error handling and retries",
        "Integrate With Azure AD for multi-tenant scenarios",
        "Integrate With Azure AD with GDPR/Privacy constraints",
        "Parameterize Credentials Securely for large datasets",
        "Parameterize Credentials Securely with query folding considerations",
        "Parameterize Credentials Securely without query folding",
        "Parameterize Credentials Securely as a reusable function",
        "Parameterize Credentials Securely optimized for incremental refresh",
        "Parameterize Credentials Securely with error handling and retries",
        "Parameterize Credentials Securely for multi-tenant scenarios",
        "Parameterize Credentials Securely with GDPR/Privacy constraints",
        "Log Access For Compliance for large datasets",
        "Log Access For Compliance with query folding considerations",
        "Log Access For Compliance without query folding",
        "Log Access For Compliance as a reusable function",
        "Log Access For Compliance optimized for incremental refresh",
        "Log Access For Compliance with error handling and retries",
        "Log Access For Compliance for multi-tenant scenarios",
        "Log Access For Compliance with GDPR/Privacy constraints"
    ],

    "Creative, Nonconventional & Interview Challenges": [
        "Build A Game Of Life Data Simulation for large datasets",
        "Build A Game Of Life Data Simulation with query folding considerations",
        "Build A Game Of Life Data Simulation without query folding",
        "Build A Game Of Life Data Simulation as a reusable function",
        "Build A Game Of Life Data Simulation optimized for incremental refresh",
        "Build A Game Of Life Data Simulation with error handling and retries",
        "Build A Game Of Life Data Simulation for multi-tenant scenarios",
        "Build A Game Of Life Data Simulation with GDPR/Privacy constraints",
        "Create A Procedural Fake Dataset for large datasets",
        "Create A Procedural Fake Dataset with query folding considerations",
        "Create A Procedural Fake Dataset without query folding",
        "Create A Procedural Fake Dataset as a reusable function",
        "Create A Procedural Fake Dataset optimized for incremental refresh",
        "Create A Procedural Fake Dataset with error handling and retries",
        "Create A Procedural Fake Dataset for multi-tenant scenarios",
        "Create A Procedural Fake Dataset with GDPR/Privacy constraints",
        "Design An M-based DSL (domain specific language) for large datasets",
        "Design An M-based DSL (domain specific language) with query folding considerations",
        "Design An M-based DSL (domain specific language) without query folding",
        "Design An M-based DSL (domain specific language) as a reusable function",
        "Design An M-based DSL (domain specific language) optimized for incremental refresh",
        "Design An M-based DSL (domain specific language) with error handling and retries",
        "Design An M-based DSL (domain specific language) for multi-tenant scenarios",
        "Design An M-based DSL (domain specific language) with GDPR/Privacy constraints",
        "Turn Wide Data Into Musical Notes for large datasets",
        "Turn Wide Data Into Musical Notes with query folding considerations",
        "Turn Wide Data Into Musical Notes without query folding",
        "Turn Wide Data Into Musical Notes as a reusable function",
        "Turn Wide Data Into Musical Notes optimized for incremental refresh",
        "Turn Wide Data Into Musical Notes with error handling and retries",
        "Turn Wide Data Into Musical Notes for multi-tenant scenarios",
        "Turn Wide Data Into Musical Notes with GDPR/Privacy constraints",
        "Create A Minimal Turing-Complete M Function for large datasets",
        "Create A Minimal Turing-Complete M Function with query folding considerations",
        "Create A Minimal Turing-Complete M Function without query folding",
        "Create A Minimal Turing-Complete M Function as a reusable function",
        "Create A Minimal Turing-Complete M Function optimized for incremental refresh",
        "Create A Minimal Turing-Complete M Function with error handling and retries",
        "Create A Minimal Turing-Complete M Function for multi-tenant scenarios",
        "Create A Minimal Turing-Complete M Function with GDPR/Privacy constraints",
        "Obfuscate And De-obfuscate Data for large datasets",
        "Obfuscate And De-obfuscate Data with query folding considerations",
        "Obfuscate And De-obfuscate Data without query folding",
        "Obfuscate And De-obfuscate Data as a reusable function",
        "Obfuscate And De-obfuscate Data optimized for incremental refresh",
        "Obfuscate And De-obfuscate Data with error handling and retries",
        "Obfuscate And De-obfuscate Data for multi-tenant scenarios",
        "Obfuscate And De-obfuscate Data with GDPR/Privacy constraints",
        "Generate Art Patterns From Numbers for large datasets",
        "Generate Art Patterns From Numbers with query folding considerations",
        "Generate Art Patterns From Numbers without query folding",
        "Generate Art Patterns From Numbers as a reusable function",
        "Generate Art Patterns From Numbers optimized for incremental refresh",
        "Generate Art Patterns From Numbers with error handling and retries",
        "Generate Art Patterns From Numbers for multi-tenant scenarios",
        "Generate Art Patterns From Numbers with GDPR/Privacy constraints",
        "Time-travel Debugging Simulation for large datasets",
        "Time-travel Debugging Simulation with query folding considerations",
        "Time-travel Debugging Simulation without query folding",
        "Time-travel Debugging Simulation as a reusable function",
        "Time-travel Debugging Simulation optimized for incremental refresh",
        "Time-travel Debugging Simulation with error handling and retries",
        "Time-travel Debugging Simulation for multi-tenant scenarios",
        "Time-travel Debugging Simulation with GDPR/Privacy constraints",
        "Self-documenting Query Generator for large datasets",
        "Self-documenting Query Generator with query folding considerations",
        "Self-documenting Query Generator without query folding",
        "Self-documenting Query Generator as a reusable function",
        "Self-documenting Query Generator optimized for incremental refresh",
        "Self-documenting Query Generator with error handling and retries",
        "Self-documenting Query Generator for multi-tenant scenarios",
        "Self-documenting Query Generator with GDPR/Privacy constraints",
        "Design An Interview Puzzle: Mystery Column for large datasets",
        "Design An Interview Puzzle: Mystery Column with query folding considerations",
        "Design An Interview Puzzle: Mystery Column without query folding",
        "Design An Interview Puzzle: Mystery Column as a reusable function",
        "Design An Interview Puzzle: Mystery Column optimized for incremental refresh",
        "Design An Interview Puzzle: Mystery Column with error handling and retries",
        "Design An Interview Puzzle: Mystery Column for multi-tenant scenarios",
        "Design An Interview Puzzle: Mystery Column with GDPR/Privacy constraints"
    ]
}

# Markdown template
template = """
# {title}

## Description
This use case demonstrates how Power Query (M) can be used for **{title}**.

## Typical Scenario
Explain when this transformation would be used in a real data pipeline.

## Key M Functions
- Example functions relevant to this scenario.

## Example Concept
Describe how the transformation would typically work inside a Power Query pipeline.
"""

# Create folders and markdown files
Path(BASE_DIR).mkdir(exist_ok=True)

counter = 0
TARGET = 1000

for category, topics in categories.items():
    if counter >= TARGET:
        break

    category_path = Path(BASE_DIR) / category
    category_path.mkdir(exist_ok=True)

    for topic in topics:
        if counter >= TARGET:
            break

        # Sanitize topic to remove characters that are invalid in filenames
        sanitized_topic = re.sub(r'[<>:"/\\|?*]', '-', topic)
        
        # Name format: 92. Topic Name
        name_with_number = f"{counter+1}. {sanitized_topic}"
        
        # Create a subfolder for this specific topic
        topic_folder_path = category_path / name_with_number
        topic_folder_path.mkdir(exist_ok=True)

        # Place the markdown file inside that subfolder
        # File name is also: 92. Topic Name.md
        file_path = topic_folder_path / f"{name_with_number}.md"

        with open(file_path, "w", encoding="utf-8") as f:
            content = template.format(title=topic.replace("_", " "))
            f.write(content)

        counter += 1

print(f"Created {counter} folders and markdown files.")